title: MOdified awesome title
author: GitHub User Xu
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I didn't see the description? where are they?
  
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
